### ISSUE TITLE
Plantear el ranking previo

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MoaLaiOrg/mundial2k10#10]
```
Muestra puntos considerando todos los partidos 0 a 0
Se visualiza en forma separada ya que no es importante.
```

Original issue reported on code.google.com by `martinporto` on 7 Jun 2010 at 7:17

**Comment by portomartin** [comment]
test

**Comment by portomartin** [comment]
via Hubstaff
User: 
Project: mundial2k10 - https://hubstaff.com/projects/69373
Date Range: 10/27/15 - 10/27/15
Work session total: 0:00:26
Grand total: 0:00:26
